[package]
name = "rc-rt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rc-core = { path = "../rc-core" }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
serde_json.workspace = true
tracing.workspace = true
