[package]
name = "rc-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rc-proto = { path = "../rc-proto" }
rc-tokenize = { path = "../rc-tokenize" }
rc-perm = { path = "../rc-perm" }
rc-algebra = { path = "../rc-algebra" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
async-trait = { workspace = true }
tracing.workspace = true
tokio-util = { workspace = true }
tokio-stream.workspace = true

[dev-dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
tokio-util = { workspace = true }
serde_json.workspace = true
