[package]
name = "rc-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rc"
path = "src/main.rs"

[dependencies]
rc-proto = { path = "../rc-proto" }
rc-config = { path = "../rc-config" }
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
