[package]
name = "dlr-receiver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dlr-core.workspace = true
dlr-coding.workspace = true
dlr-compress.workspace = true
bytes.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
rayon.workspace = true

[dev-dependencies]
dlr-shim.workspace = true

[lib]
path = "src/lib.rs"
