[package]
name = "dlr-prune"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dlr-core.workspace = true
dlr-receiver.workspace = true
bytes.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
rayon.workspace = true
ahash.workspace = true

[dev-dependencies]
dlr-compress.workspace = true

[lib]
path = "src/lib.rs"
