[package]
name = "rc-ctx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rc-core = { path = "../rc-core" }
rc-proto = { path = "../rc-proto" }
rc-tokenize = { path = "../rc-tokenize" }
rc-algebra = { path = "../rc-algebra" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3"
